import { google } from "googleapis";
import { randomUUID } from "crypto";
import oauth2Client from "../../../middlewares/googleAuthMiddleware";
import { createLogger } from "../../../utils/logger";
import { processNewFiles } from "./fileProcessingController";

const log = createLogger("Mindmapper");


// Temporary storage for watch channel state
type WatchChannelState = {
    channelId: string; // This is to store the webhook id
    resourceId: string; // This is the sent by google which we need to store
    pageToken: string; // This is generated by our backend by google
    folderId: string; // This is the folder that the user selected
    folderName: string; // Same but the name
    expiration: number; // This is the expiration
    email: string;
};

let activeChannel: WatchChannelState | null = null;


export function getGoogleAccessToken() {
    return oauth2Client.credentials?.access_token;
}

export function getGoogleClientId() {
    return process.env.GOOGLE_CLIENT_ID;
}

export function getGoogleLoginUrl() {
    const SCOPE = [
        "https://www.googleapis.com/auth/drive.metadata.readonly",
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/userinfo.email",
    ];

    const authUrl = oauth2Client.generateAuthUrl({
        access_type: "offline",
        scope: SCOPE,
        prompt: "consent select_account",
    });

    return authUrl;
}

export async function handleGoogleCallback(req: any) {
    const error = req.query.error as string | undefined;
    if (error) {
        return false;
    }

    const code = req.query.code as string | undefined;
    if (!code) {
        return false;
    }

    const { tokens } = await oauth2Client.getToken(code);
    oauth2Client.setCredentials(tokens);
    const oauth2 = google.oauth2({
        auth: oauth2Client,
        version: "v2",
    });

    try {
        const { data } = await oauth2.userinfo.get();
        (global as any).googleUserEmail = data.email;
    } catch (err) {
        console.error("Failed to get user email:", err);
    }
    return true;
}

/**
 * Register a Google Drive changes watch channel for the given folder.
 * Google will POST to our webhook endpoint whenever anything changes.
 */
export async function setupDriveWatch(folderId: string, folderName: string, email: string) {
    const drive = google.drive({ version: "v3", auth: oauth2Client });

    // Get a baseline page token so we only see changes from NOW onward
    const tokenRes = await drive.changes.getStartPageToken({});
    const pageToken = tokenRes.data.startPageToken;
    if (!pageToken) {
        throw new Error("Could not retrieve a start page token from Drive API");
    }

    // Build the public webhook URL
    const webhookBase = process.env.GOOGLE_WEBHOOK_BASE_URL;
    if (!webhookBase) {
        throw new Error("GOOGLE_WEBHOOK_BASE_URL is not defined");
    }

    // This just links to our backend endpoint
    const webhookAddress = `${webhookBase}/api/mindmapper/google/drive-webhook`;

    // Register the watch channel
    const channelId = randomUUID();
    const watchRes = await drive.changes.watch({
        pageToken,
        requestBody: {
            id: channelId,
            type: "web_hook",
            address: webhookAddress,
        },
    });

    const { resourceId, expiration } = watchRes.data;
    if (!resourceId) {
        throw new Error("Drive watch did not respond with a resourceId");
    };

    // Store channel state in memory (Change this to a database)
    activeChannel = {
        channelId,
        resourceId,
        pageToken,
        folderId,
        folderName,
        expiration: Number(expiration ?? 0),
        email,
    };

    log.info(`Drive watch registered, channel: ${channelId}, expires: ${new Date(Number(expiration)).toLocaleString('en-SG', { timeZone: 'Asia/Singapore' })}`);
}

/**
 * Handle an incoming Drive push-notification webhook.
 * Google always expects a 200 response quickly, so do the heavy lifting async.
 */
export async function handleDriveWebhook(headers: Record<string, string | string[] | undefined>) {
    // These are the params google uses
    const channelId = headers["x-goog-channel-id"] as string;
    const resourceState = headers["x-goog-resource-state"] as string;

    // "sync" fires immediately after watch registration
    if (resourceState === "sync") {
        log.info(`Drive webhook: sync ping received for channel ${channelId} — ignored`);
        return;
    }

    // Change this part to check with the database
    if (!activeChannel || channelId !== activeChannel.channelId) {
        log.warn(`Drive webhook: received notification for unknown channel ${channelId}`);
        return;
    }

    log.info(`Drive webhook: change detected (state: ${resourceState})`);
    processNewFiles(activeChannel.pageToken, activeChannel.folderId, activeChannel.folderName, activeChannel.email);
}